### ISSUE TITLE
Other icon for iFrame mode close button

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#155]
> I really like the feature but I think the icon might be a little confusing. If we think of the panel iframe overlay as a modal the close icon indicates that it closes the modal, not that it stays in the panel.
>
> The first icon that comes to mind is to use a kind of pin icon instead:
http://fortawesome.github.io/Font-Awesome/icon/thumb-tack/
>
> ...to pin the panel to the screen.

**Comment by distantnative** [comment]
Not sure about this one, @jenstornell. The thumb tack would rather suggest to pin the panelBar and not to remove it. Also, isn't it pretty consistent that the close button removes the panelBar and gives access to what's beneath: in iFrame mode the pure panel?

**Comment by jenstornell** [comment]
Ahh, I get your idea about this.

What makes it confusing is this. When on frontend the panelbar feels like a minimal version of the panel (the real panel). When in edit mode the panelbar still feels like the panel.

When closing what we feel is the panel, on frontend or backend, I expected it to close the panel (including panelbar) and get back to the frontend. Do you understand what I'm getting at? That the panel and panelbar feels like the same thing and that the frontend are always below.

As for the function the X does not do the same thing. On the frontend it hides the panelbar. In backend it redirects to the panel which is a completly different thing, because then you are at another url and not in frontend anymore and there is no way to get the panelbar back (except for preview in panel). That's why I also think the consistancy fail.

**In my eyes it does:**

- Does not do what I expect
- Does not do the same as the same icon on the frontend

Maybe just think about it one more time before closing it?

**Comment by jenstornell** [comment]
The pin-icon I suggested was for the idea that the panelbar and the panel feels bundled together, the same thing. In that perspective you don't pin the panelbar, you pin the panel. As a user I don't see a bar in admin-mode, just the panel.

**Comment by distantnative** [comment]
Fair enough. Just added it to the v1 develop branch.
