### ISSUE TITLE
Wanted: Idea for elements

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#23]
What kind of elements (buttons, dropdowns, links) would you like to see as potential default ones?

**Comment by jenstornell** [comment]
There are some ideas, but I cannot tell you if I will need them or not in the future:

## Edit

- Edit child pages list, children to current page, if any
- Edit images to current page

## Information

- This page is cached, or not
- Loading time (can be wrong because of logged in)
- Number of images
- Number of children
- Number of siblings

I don't know how info should be presented without bloating it. I would probably want to have the first two of them in the list.

## Info box

I could be nice to have a helper that is an info box, maybe like a dropdown but just for plain information.

I would probably add the SEO title tag and SEO meta description in there.

**Comment by distantnative** [comment]
Reading this, I def see the need for a textbox helper: label etc. like a dropbox, but instead a list just a div that can be filled with more code, text...

**Comment by jenstornell** [comment]
A "inline" text element for not links in the bar. Read more here:

https://github.com/distantnative/panel-bar/issues/38
